flow:
	g++ -I/usr/include/opencv4 -std=c++11 -o flow_run main.cpp src/flow_opencv.cpp src/flow_px4.cpp src/optical_flow.cpp src/px4flow.cpp src/trackFeatures.cpp -lopencv_core -lopencv_imgproc -lopencv_videoio -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_video
